## Based from the content at https://github.com/rancher/k3s/blob/master/docker-compose.yml

version: '3'
services:
  server:
    image: rancher/k3s:v1.17.4-k3s1
    command: server --disable-agent --no-deploy traefik
    environment:
      - K3S_CLUSTER_SECRET=secret
      - K3S_KUBECONFIG_OUTPUT=/output/kubeconfig.yaml
      - K3S_KUBECONFIG_MODE=666
    volumes:
      - k3s-server:/var/lib/rancher/k3s
      - .:/output
    ports:
      - 6443:6443

  node:
    image: rancher/k3s:v1.17.4-k3s1
    tmpfs:
      - /run
      - /var/run
    privileged: true
    depends_on:
      - server
    ports:
      - 8080:80
      - 8443:443
    environment:
      - K3S_URL=https://server:6443
      - K3S_CLUSTER_SECRET=secret

volumes:
  k3s-server: {}
