apiVersion: v1
kind: DeploymentConfig
metadata:
  labels:
    app: 3scale-istio-adapter
  name: 3scale-istio-adapter
spec:
  replicas: 1
  selector:
    app: 3scale-istio-adapter
    deploymentconfig: 3scale-istio-adapter
  strategy:
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      labels:
        app: 3scale-istio-adapter
        deploymentconfig: 3scale-istio-adapter
    spec:
      containers:
      - image: quay.io/3scale/3scaleistioadapter:0.1
        imagePullPolicy: Always
        name: 3scale-istio-adapter
        ports:
        - containerPort: 3333
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
  triggers:
  - type: ConfigChange