apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: 3scale-istio-adapter
  name: 3scale-istio-adapter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: 3scale-istio-adapter
  strategy:
    rollingUpdate:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: 3scale-istio-adapter
    spec:
      containers:
      - image: quay.io/3scale/3scaleistioadapter:0.2
        imagePullPolicy: Always
        name: 3scale-istio-adapter
        ports:
        - containerPort: 3333
          protocol: TCP
          name: adapter
        - containerPort: 8080
          protocol: TCP
          name: prometheus
        env:
        - name: "THREESCALE_LOG_JSON"
          value: "true"
        - name: "THREESCALE_REPORT_METRICS"
          value: "true"
        - name: "THREESCALE_METRICS_PORT"
          value: "8080"
        resources: {}
        terminationMessagePath: /dev/termination-log
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
  triggers:
  - type: ConfigChange
