# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11
    steps:
      - checkout

      - restore_cache:
          keys:
            - go-mod-v1-{{ checksum "go.sum" }}

      - run:
          name: Run unit tests
          command: |
            make unit

      - run:
          name: Run integration tests
          command: |
            make integration

      - save_cache:
          key: go-mod-v1-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"

      - run:
          name: Merge coverage profiles and pipe to Codecov
          command: |
            go get github.com/wadey/gocovmerge
            gocovmerge _output/integration.cov _output/unit.cov > coverage.txt
            bash <(curl -s https://codecov.io/bash)
