# handler for adapter Threescale
apiVersion: "config.istio.io/v1alpha2"
kind: handler
metadata:
 name: threescalehandler
 namespace: istio-system
spec:
 adapter: threescale
 params:
   service_id: "XXXXXXXXXXXX"
   system_url: "https://XXXXXXX-admin.3scale.net/"
   access_token: "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
 connection:
   address: "threescaleistioadapter:3333"
---

# instance for template authorization
apiVersion: "config.istio.io/v1alpha2"
kind: instance
metadata:
 name: threescaleauthorizationtemplate
 namespace: istio-system
spec:
 template: authorization
 params:
   action:
     namespace: destination.namespace | ""
     service: destination.service | ""
     path: request.path | ""
     method: request.method | ""
     properties:
       user-key: request.headers["user-key"] | ""
---

# rule to dispatch to handler h1
apiVersion: "config.istio.io/v1alpha2"
kind: rule
metadata:
 name: usethreescale
 namespace: istio-system
spec:
 actions:
 - handler: threescalehandler.istio-system
   instances:
   - threescaleauthorizationtemplate
---

