apiVersion: v1
kind: ConfigMap
metadata:
  name: 3scale-istio-adapter-conf
data:
  log_json: "true"
  log_level: "info"
  log_grpc: "false"
  metrics.report: "true"
  metrics.port: "8080"
  # All durations are in seconds unless specified as otherwise
  system.cache_ttl: "300"
  system.cache_refresh_interval: "180"
  system.cache_max_size: "1000"
  system.cache_refresh_retries: "1"
  client.allow_insecure_connections: "false"
  client.timeout: "10"
  grpc.max_conn_timeout: "60"
  backend.enable_cache: "false"
  backend.cache_flush_interval: "15"
  backend.policy_fail_closed: "true"
