# Refer to https://golang.github.io/dep/docs/Gopkg.toml.html for details

[[constraint]]
  name = "github.com/gogo/protobuf"
  version = "1.1.1"

[[constraint]]
  name = "google.golang.org/grpc"
  version = "1.14.0"

[[constraint]]
  name = "istio.io/istio"
  version = "1.0.5"

[[constraint]]
  name = "github.com/3scale/3scale-go-client"
  version = "v0.0.1"

[[constraint]]
  name = "github.com/3scale/3scale-porta-go-client"
  version = "v0.0.2"

# Override provided here to mitigate the issue caused by https://github.com/istio/istio/pull/10321
# Revert to constraint at next available opportunity
[[override]]
  name = "github.com/prometheus/client_golang"
  version = "0.9.2"

[prune]
  go-tests = true
