# Refer to https://golang.github.io/dep/docs/Gopkg.toml.html for details

[[constraint]]
  name = "github.com/gogo/protobuf"
  version = "1.1.1"

[[constraint]]
  name = "google.golang.org/grpc"
  version = "1.14.0"

[[constraint]]
  name = "istio.io/istio"
  version = "1.0.0"

[[constraint]]
  name = "github.com/3scale/3scale-go-client"
  version = "v0.0.1"

[[constraint]]
  name = "github.com/3scale/3scale-porta-go-client"
  version = "v0.0.1"

[[constraint]]
  name = "github.com/prometheus/client_golang"
  version = "0.9.1"

[prune]
  go-tests = true
